// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBphUyWQqgCDhPk5rIaTNLThhmgfjlZjHY',
    appId: '1:518533842801:web:904c155c7ca10c084a58d0',
    messagingSenderId: '518533842801',
    projectId: 'mj-stories-169807',
    authDomain: 'mj-stories-169807.firebaseapp.com',
    databaseURL: 'https://mj-stories-169807.firebaseio.com',
    storageBucket: 'mj-stories-169807.appspot.com',
    measurementId: 'G-M14TDK35P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK_heLfw8j--4QysHHChAYTInra-JDnvM',
    appId: '1:518533842801:android:dc610ed5e3a491b5',
    messagingSenderId: '518533842801',
    projectId: 'mj-stories-169807',
    databaseURL: 'https://mj-stories-169807.firebaseio.com',
    storageBucket: 'mj-stories-169807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1R0bZfLO5QlVee4zI7-c9SYsEm4jeaeQ',
    appId: '1:518533842801:ios:cd3558a55bf4fc3e',
    messagingSenderId: '518533842801',
    projectId: 'mj-stories-169807',
    databaseURL: 'https://mj-stories-169807.firebaseio.com',
    storageBucket: 'mj-stories-169807.appspot.com',
    androidClientId: '518533842801-2p7p2k05h4dh1bdel16g32d3rlh7cg7u.apps.googleusercontent.com',
    iosClientId: '518533842801-htuivakbfj06u08rf3rlno2abqcll7id.apps.googleusercontent.com',
    iosBundleId: 'com.earlystart.monkeyjunior.story',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1R0bZfLO5QlVee4zI7-c9SYsEm4jeaeQ',
    appId: '1:518533842801:ios:44a792211067c73c4a58d0',
    messagingSenderId: '518533842801',
    projectId: 'mj-stories-169807',
    databaseURL: 'https://mj-stories-169807.firebaseio.com',
    storageBucket: 'mj-stories-169807.appspot.com',
    androidClientId: '518533842801-2p7p2k05h4dh1bdel16g32d3rlh7cg7u.apps.googleusercontent.com',
    iosClientId: '518533842801-6q53qjiic4b46o893h5r5htepuml9gft.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyStories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2421c1gBSY3ldQCXnwj6VEmHBYwZjsmg',
    appId: '1:518533842801:web:7eaa3cecbfd3bd714a58d0',
    messagingSenderId: '518533842801',
    projectId: 'mj-stories-169807',
    authDomain: 'mj-stories-169807.firebaseapp.com',
    databaseURL: 'https://mj-stories-169807.firebaseio.com',
    storageBucket: 'mj-stories-169807.appspot.com',
    measurementId: 'G-22LFP0Q3DB',
  );

}