# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Get version information"
  lane :get_version do
    version_code = get_build_number(xcodeproj: "Runner.xcodeproj")
    version_name = get_version_number(xcodeproj: "Runner.xcodeproj")
    
    UI.message "Version Code: #{version_code}"
    UI.message "Version Name: #{version_name}"
    
    {
      version_code: version_code,
      version_name: version_name
    }
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Lấy version code và version name
    version_code = get_build_number(xcodeproj: "Runner.xcodeproj")
    version_name = get_version_number(xcodeproj: "Runner.xcodeproj")
    
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
